version: "3.9"
services:
  script-server:
    build:
      dockerfile: Dockerfile
    image: davis8988/script-server:v1.17.1
    container_name: script-server
    restart: always
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/conf/conf.json:/app/conf/conf.json
      # - ./conf/runners/:/app/conf/runners
      # - ./conf/scripts/:/app/conf/scripts
      # - ./conf/logs/:/app/conf/scripts
